import { DeepnoteBlock as BaseDeepnoteBlock, DeepnoteFile as BaseDeepnoteFile } from '@deepnote/blocks';

/**
 * Re-export base types from @deepnote/blocks for convenience.
 */
export type { BaseDeepnoteBlock, BaseDeepnoteFile };

/**
 * Extended DeepnoteBlock with Stage 1 snapshot fields.
 * These fields are optional and backward compatible.
 */
export interface DeepnoteBlock extends BaseDeepnoteBlock {
    /** SHA-256 hash of block content (prefixed with "sha256:") */
    contentHash?: string;

    /** ISO 8601 timestamp when block execution started */
    executionStartedAt?: string;

    /** ISO 8601 timestamp when block execution finished */
    executionFinishedAt?: string;
}

/**
 * Extended DeepnoteFile with Stage 1 snapshot fields.
 * Uses environment and execution types from @deepnote/blocks.
 * The project field is extended to use our DeepnoteBlock type.
 */
export interface DeepnoteFile extends Omit<BaseDeepnoteFile, 'project'> {
    /** Project data with extended block types */
    project: Omit<BaseDeepnoteFile['project'], 'notebooks'> & {
        notebooks: Array<
            Omit<BaseDeepnoteFile['project']['notebooks'][number], 'blocks'> & {
                blocks: DeepnoteBlock[];
            }
        >;
    };
}

/**
 * Alias for DeepnoteFile for backward compatibility.
 * @deprecated Use DeepnoteFile instead.
 */
export type DeepnoteProject = DeepnoteFile;

/**
 * Represents a single notebook within a Deepnote project.
 * Extracted from DeepnoteFile['project']['notebooks'][number].
 */
export type DeepnoteNotebook = DeepnoteFile['project']['notebooks'][number];

/**
 * Represents output data generated by executing a code block.
 */
export type DeepnoteOutput =
    | {
          data?: Record<string, unknown>;
          execution_count?: number;
          metadata?: Record<string, unknown>;
          output_type: 'display_data' | 'execute_result';
          text?: string;
      }
    | {
          name?: string;
          text?: string;
      }
    | {
          name?: string;
          output_type: 'stream';
          text?: string;
      }
    | {
          ename?: string;
          evalue?: string;
          output_type: 'error';
          text?: string;
          traceback?: string[];
      }
    | {
          output_type: string;
          text?: string;
          [key: string]: unknown;
      };
