/**
 * Utility functions for Deepnote block ID and sorting key generation
 */

import { NotebookCell, NotebookCellData } from 'vscode';

import type { Pocket } from '../../platform/deepnote/pocket';

export function parseJsonWithFallback(value: string, fallback?: unknown): unknown | null {
    try {
        return JSON.parse(value);
    } catch (error) {
        return fallback ?? null;
    }
}

/**
 * Generate a random hex ID for blocks (32 character hex string)
 */
export function generateBlockId(): string {
    const chars = '0123456789abcdef';
    let id = '';
    for (let i = 0; i < 32; i++) {
        id += chars[Math.floor(Math.random() * chars.length)];
    }
    return id;
}

/**
 * Returns true if the cell is backed by an agent block.
 *
 * Lives here rather than next to the execution handler so callers that only need the predicate
 * don't pull `@deepnote/runtime-core` into their module graph.
 */
export function isAgentCell(cell: NotebookCell): boolean {
    const pocket = cell.metadata?.__deepnotePocket as Pocket | undefined;

    return pocket?.type === 'agent';
}

/**
 * Returns true if the cell metadata indicates an ephemeral cell (auto-generated by agent).
 */
export function isEphemeralCell(cell: NotebookCell | NotebookCellData): boolean {
    return cell.metadata?.is_ephemeral === true;
}

/**
 * Returns the id of the block a cell is backed by, or undefined for a cell that has never been
 * serialized.
 *
 * `__deepnoteBlockId` wins because VS Code may rewrite `id`, which is why the converter mirrors it.
 * `deepnoteBlockId` is a third name the fallback-cell path writes; it is only ever set alongside the
 * other two, so it resolves nothing new in practice and exists to tolerate metadata that has lost
 * them. Losing an id here is worse than reading a redundant one: callers mint a fresh one, which
 * reassigns the block on save.
 */
export function getBlockId(cell: NotebookCell | NotebookCellData): string | undefined {
    return (
        (cell.metadata?.__deepnoteBlockId as string | undefined) ||
        (cell.metadata?.id as string | undefined) ||
        (cell.metadata?.deepnoteBlockId as string | undefined)
    );
}

/**
 * Returns the id of the agent block that generated this ephemeral cell, or undefined if the cell
 * isn't agent-generated scratch.
 */
export function getEphemeralCellAgentSourceBlockId(cell: NotebookCell): string | undefined {
    return isEphemeralCell(cell) ? (cell.metadata?.agent_source_block_id as string | undefined) : undefined;
}

/**
 * Generate sorting key based on index (format: a0, a1, ..., a99, b0, b1, ...)
 */
export function generateSortingKey(index: number): string {
    const alphabet = 'abcdefghijklmnopqrstuvwxyz';
    const letterIndex = Math.floor(index / 100);
    const letter = letterIndex < alphabet.length ? alphabet[letterIndex] : 'z';
    const number = index % 100;
    return `${letter}${number}`;
}
