import { DeepnoteBlock, DeepnoteFile } from '@deepnote/blocks';

/**
 * Re-export types from @deepnote/blocks for convenience.
 */
export type { DeepnoteBlock, DeepnoteFile };

/**
 * Alias for DeepnoteFile for backward compatibility.
 * @deprecated Use DeepnoteFile instead.
 */
export type DeepnoteProject = DeepnoteFile;

/**
 * Represents a single notebook within a Deepnote project.
 * Extracted from DeepnoteFile['project']['notebooks'][number].
 */
export type DeepnoteNotebook = DeepnoteFile['project']['notebooks'][number];

/**
 * Represents output data generated by executing a code block.
 */
export type DeepnoteOutput =
    | {
          data?: Record<string, unknown>;
          execution_count?: number;
          metadata?: Record<string, unknown>;
          output_type: 'display_data' | 'execute_result';
          text?: string;
      }
    | {
          name?: string;
          text?: string;
      }
    | {
          name?: string;
          output_type: 'stream';
          text?: string;
      }
    | {
          ename?: string;
          evalue?: string;
          output_type: 'error';
          text?: string;
          traceback?: string[];
      }
    | {
          output_type: string;
          text?: string;
          [key: string]: unknown;
      };
