import {
    CancellationToken,
    Disposable,
    EventEmitter,
    NotebookCell,
    NotebookCellStatusBarItem,
    NotebookCellStatusBarItemProvider,
    NotebookEdit,
    NotebookRange,
    WorkspaceEdit,
    commands,
    l10n,
    notebooks,
    window,
    workspace
} from 'vscode';
import { injectable } from 'inversify';

import { IExtensionSyncActivationService } from '../../platform/activation/types';
import { getEphemeralCellAgentSourceBlockId, isEphemeralCell } from './dataConversionUtils';

const CLEAR_EPHEMERAL_BLOCKS_COMMAND = 'deepnote.clearEphemeralBlocks';

const EPHEMERAL_INDICATOR_PRIORITY = 1000;
const CLEAR_EPHEMERAL_PRIORITY = 990;

@injectable()
export class EphemeralCellStatusBarProvider
    implements NotebookCellStatusBarItemProvider, IExtensionSyncActivationService
{
    private readonly disposables: Disposable[] = [];
    private readonly _onDidChangeCellStatusBarItems = new EventEmitter<void>();

    public readonly onDidChangeCellStatusBarItems = this._onDidChangeCellStatusBarItems.event;

    public activate(): void {
        this.disposables.push(notebooks.registerNotebookCellStatusBarItemProvider('deepnote', this));

        this.disposables.push(
            workspace.onDidChangeNotebookDocument((e) => {
                if (e.notebook.notebookType === 'deepnote') {
                    this._onDidChangeCellStatusBarItems.fire();
                }
            })
        );

        this.disposables.push(
            commands.registerCommand(CLEAR_EPHEMERAL_BLOCKS_COMMAND, async (cell?: NotebookCell) => {
                const activeCell = cell || this.getActiveCell();
                if (activeCell) {
                    await this.clearEphemeralBlocks(activeCell);
                }
            })
        );

        this.disposables.push(this._onDidChangeCellStatusBarItems);
    }

    /** Deletes the ephemeral cells the same agent block generated, after a modal confirmation. */
    public async clearEphemeralBlocks(cell: NotebookCell): Promise<void> {
        if (!isEphemeralCell(cell)) {
            return;
        }

        const cellsToClear = this.getCellsToClear(cell);

        const confirmation = await window.showWarningMessage(
            l10n.t('Clear {0} ephemeral block(s) from this notebook?', cellsToClear.length),
            { modal: true },
            l10n.t('Clear')
        );

        if (confirmation !== l10n.t('Clear')) {
            return;
        }

        // Descending so each deletion's index still addresses the cell it was computed from.
        const deletions = [...cellsToClear]
            .sort((a, b) => b.index - a.index)
            .map((target) => NotebookEdit.deleteCells(new NotebookRange(target.index, target.index + 1)));

        const edit = new WorkspaceEdit();
        edit.set(cell.notebook.uri, deletions);

        if (!(await workspace.applyEdit(edit))) {
            void window.showErrorMessage(l10n.t('Failed to clear ephemeral blocks'));
        }
    }

    public dispose(): void {
        this.disposables.forEach((d) => d.dispose());
    }

    public provideCellStatusBarItems(
        cell: NotebookCell,
        token: CancellationToken
    ): NotebookCellStatusBarItem[] | undefined {
        if (token.isCancellationRequested) {
            return undefined;
        }

        if (!isEphemeralCell(cell)) {
            return undefined;
        }

        const agentSourceBlockId = cell.metadata?.agent_source_block_id as string | undefined;

        return [this.createEphemeralIndicatorItem(agentSourceBlockId ?? null), this.createClearEphemeralItem(cell)];
    }

    private createClearEphemeralItem(cell: NotebookCell): NotebookCellStatusBarItem {
        return {
            text: `$(trash) ${l10n.t('Clear ephemeral blocks')}`,
            alignment: 1,
            priority: CLEAR_EPHEMERAL_PRIORITY,
            tooltip: l10n.t('Remove the ephemeral blocks generated by this agent block'),
            command: {
                title: l10n.t('Clear ephemeral blocks'),
                command: CLEAR_EPHEMERAL_BLOCKS_COMMAND,
                arguments: [cell]
            }
        };
    }

    private createEphemeralIndicatorItem(agentSourceBlockId: string | null): NotebookCellStatusBarItem {
        const tooltipLines = [l10n.t('Auto-generated ephemeral block')];
        if (agentSourceBlockId) {
            tooltipLines.push(l10n.t('Source agent block: {0}', agentSourceBlockId));
        }

        return {
            text: `$(sparkle) ${l10n.t('Ephemeral')}`,
            alignment: 1,
            priority: EPHEMERAL_INDICATOR_PRIORITY,
            tooltip: tooltipLines.join('\n')
        };
    }

    private getActiveCell(): NotebookCell | undefined {
        const activeEditor = window.activeNotebookEditor;
        if (activeEditor && activeEditor.selection) {
            return activeEditor.notebook.cellAt(activeEditor.selection.start);
        }

        return undefined;
    }

    /** Siblings of the same agent run; just the cell itself when it records no source block. */
    private getCellsToClear(cell: NotebookCell): NotebookCell[] {
        const agentSourceBlockId = getEphemeralCellAgentSourceBlockId(cell);

        if (!agentSourceBlockId) {
            return [cell];
        }

        return cell.notebook
            .getCells()
            .filter((candidate) => getEphemeralCellAgentSourceBlockId(candidate) === agentSourceBlockId);
    }
}
